DEFAULT = 'United States of America'
CONTINENT_ORDER = ["N. America", "C. America/Carib.", "S. America", "Europe", "Africa", "Asia", "Oceania", ]

COUNTRIES = {
    "N. America": [
        DEFAULT, 
        'Canada', 
        'Mexico', 
        ],
    "Europe": [
        'Albania',
        'Andorra',
        'Austria',
        'Belarus',
        'Belgium',
        'Bosnia and Herzegovina',
        'Bulgaria',
        'Croatia',
        'Czech Republic',
        'Denmark',
        'Estonia',
        'Finland',
        'France',
        'Germany',
        'Gibraltar',
        'Greece',
        'Hungary',
        'Iceland',
        'Ireland',
        'Italy',
        'Latvia',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Macedonia',
        'Malta',
        'Moldova',
        'Monaco',
        'Montenegro',
        'Netherlands',
        'Norway',
        'Poland',
        'Portugal',
        'Romania',
        'Russia',
        'San Marino',
        'Serbia',
        'Slovakia',
        'Slovenia',
        'Spain',
        'Sweden',
        'Switzerland',
        'Ukraine',
        'United Kingdom',
        ],
    "C. America/Carib.": [
        'Anguilla',
        'Antigua and Barbuda',
        'Aruba',
        'Bahamas',
        'Barbados',
        'Belize',
        'Bermuda',
        'Cayman Is.',
        'Costa Rica',
        'Cuba',
        'Dominica',
        'Dominican Republic',
        'El Salvador',
        'Greenland',
        'Grenada',
        'Guadeloupe',
        'Guatemala',
        'Haiti',
        'Honduras',
        'Jamaica',
        'Martinique',
        'Montserrat',
        'Netherlands Antilles',
        'Nicaragua',
        'Panama',
        'Puerto Rico',
        'St. Barthelemy',
        'St. Kitts and Nevis',
        'St. Lucia',
        'St. Martin',
        'St. Pierre and Miquelon',
        'St. Vincent and the Grenadines',
        'Trinidad and Tobago',
        'Turks and Caicos Is.',
        'Virgin Is. (U.K.)',
        'Virgin Is. (U.S.)',
        ],
    "S. America": [
        'Argentina',
        'Bolivia',
        'Brazil',
        'Chile',
        'Colombia',
        'Ecuador',
        'Falkland Is.',
        'French Guiana',
        'Guyana',
        'Paraguay',
        'Peru',
        'Suriname',
        'Uruguay',
        'Venezuela',
        ],
    "Asia": [
        'Afghanistan',
        'Armenia',
        'Azerbaijan',
        'Bahrain',
        'Bangladesh',
        'Bhutan',
        'Brunei Darussalam',
        'Cambodia',
        'China',
        'Cyprus',
        'Georgia',
        'Hong Kong',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Israel',
        'Japan',
        'Jordan',
        'Kazakhstan',
        'Korea, North',
        'Korea, South',
        'Kuwait',
        'Kyrgyz Republic',
        'Laos',
        'Lebanon',
        'Macao',
        'Malaysia',
        'Maldives',
        'Mongolia',
        'Myanmar',
        'Nepal',
        'Oman',
        'Pakistan',
        'Palestine',
        'Philippines',
        'Qatar',
        'Saudi Arabia',
        'Singapore',
        'Sri Lanka',
        'Syria',
        'Taiwan',
        'Tajikistan',
        'Thailand',
        'Timor-Leste',
        'Turkey',
        'Turkmenistan',
        'United Arab Emirates',
        'Uzbekistan',
        'Vietnam',
        'Yemen',
        ],
    "Africa": [
        'Algeria',
        'Angola',
        'Benin',
        'Botswana',
        'Burkina Faso',
        'Burundi',
        'Cameroon',
        'Cape Verde',
        'Central African Republic',
        'Chad',
        'Comoros',
        'Congo',
        'Congo',
        'Cote d\'Ivoire',
        'Djibouti',
        'Egypt',
        'Equatorial Guinea',
        'Eritrea',
        'Ethiopia',
        'Gabon',
        'Gambia',
        'Ghana',
        'Guinea-Bissau',
        'Guinea',
        'Kenya',
        'Lesotho',
        'Liberia',
        'Libya',
        'Madagascar',
        'Malawi',
        'Mali',
        'Mauritania',
        'Mauritius',
        'Mayotte',
        'Morocco',
        'Mozambique',
        'Namibia',
        'Niger',
        'Nigeria',
        'Reunion',
        'Rwanda',
        'Sao Tome and Principe',
        'Senegal',
        'Seychelles',
        'Sierra Leone',
        'Somalia',
        'South Africa',
        'St. Helena',
        'Sudan',
        'Swaziland',
        'Tanzania',
        'Togo',
        'Tunisia',
        'Uganda',
        'Western Sahara',
        'Zambia',
        'Zimbabwe',
        ],
    "Oceania": [
        'Australia',
        'Cook Is.',
        'Fiji',
        'French Polynesia',
        'Guam',
        'Kiribati',
        'Marshall Is.',
        'Micronesia',
        'Nauru',
        'New Caledonia',
        'New Zealand',
        'Niue',
        'Norfolk Island',
        'Northern Mariana Is.',
        'Palau',
        'Papua New Guinea',
        'Pitcairn Is.',
        'Samoa, American',
        'Samoa, Independent',
        'Solomon Is.',
        'Tokelau',
        'Tonga',
        'Tuvalu',
        'U.S. Minor Outlying Is.',
        'Vanuatu',
        'Wallis and Futuna',
        ],

}
